### PR TITLE
Ussuri backport multienv

### PR DESCRIPTION
**Pull request by darmach**
Backport of multi-env feature from upstream/master:

 - Add documentation for multiple environments

    Change-Id: Ie74b1ee61d4cfa19ea710153694349c7ea61d78e
    Story: 2002009
    Task: 40039
    (Cherry pick 1a20aa071b135b4a3d7a78824c6e26360c178203)

 - Exit when environment clashes are detected

    When running kolla-ansible using a Kayobe environment, write the
    environment name to $KOLLA_CONFIG_PATH/.environment. In later
    executions, check that the environment name is the same. Warn user to
    clean up $KOLLA_CONFIG_PATH otherwise.

    Change-Id: Ibbb1fdcad4034620ff8fbfe184d803bcc86f53f9
    Story: 2002009
    Task: 42185
    (Cherry pick 18a25fdb0580f0d68c93b2c63de99554034e19a7)

 - Detect multiple inventories automatically

    When inventory arguments are not passed but an environment is specified,
    detect if there are inventory directories present in the shared Kayobe
    configuration directory and in the environment directory. Using
    os.path.exists() is sufficient because we validate these paths later
    with utils.is_readable_dir().

    Change-Id: Ieb2b7ff07cd43029399e9e19002b82940246f8c4
    Story: 2002009
    Task: 41739
    (Cherry pick ea54f822999e6bc43e195f38cfd66caf05fc10ef)

 - Support passing multiple Kayobe inventory arguments

    Change-Id: I875d73cfe056dc505beffdec9bf348b3dc8bd910
    Story: 2002009
    Task: 41738
    (Cherry pick c15ed69b18dfbf4de69d8bf2ca01c934cb4fbf54)

 - Add a command to create a new Kayobe environment

    Change-Id: I2f33bda5f2f84bbbb0f40240d2575a0b69ddceea
    Story: 2002009
    Task: 40038
    (Cherry pick 2bc568debb2a6f7d3e0b28e1568b5f27eded27d3)

 - Support multiple environments from a single configuration

    Change-Id: I848d834aa36943027c126e26e93e4a4680521144
    Story: 2002009
    Task: 40037
    (Cherry picked 14196369301dd6aa41dc897f908610720a4291b0)

### CODE REVIEW

**Comment by markgoddard** [comment]
Was this a clean set of backports?

**Comment by markgoddard** [comment]
I think this needs to go to Victoria first.

**Comment by darmach** [comment]
> Was this a clean set of backports?

Yep, cherry picked without any conflicts.

> I think this needs to go to Victoria first.

Makes sense, will open another pull to Victoria

**Comment by darmach** [comment]
Opened a pull to Victoria too: https://github.com/stackhpc/kayobe/pull/215

**Comment by darmach** [comment]
Added missing:

- Exclude shared directories when creating environments
  If we try to create a new environment from a shared configuration inside
the same repository, we can produce an infinite loop by copying the
environment into itself. Ignore any existing environments directory
during environment creation.

  Change-Id: Ic9d3d03192f515a055e41351a0bf25da7a7b0684
Story: 2002009
Task: 40038
(Cherry picked b78218a)

 - Add release note for multiple environments
Warn in the documentation that it is an experimental feature.

   Change-Id: I46ea01ef9a3f6e322489e6d2a28f99d05656e0f2
 (Cherry picked 079704a)
 
- Allow passing arguments to dev/environment-setup.sh
Arguments are passed through to kayobe-env in kayobe-config, which
allows to set the Kayobe environment.

  Change-Id: I4c72e32e5379237340284a09874b0c500e41ad0f
  (Cherry picked 7b16300c8f1af73809f2d18cd75a172c562ad4d1)

**Review by markgoddard — APPROVED** [review]

**Review by priteau — APPROVED** [review]

**Pull request merged**
