### PR TITLE
networks.py: Added xmit_hash_policy to bonding option filters.

### PR DESCRIPTION
**Pull request by jpds**

### CODE REVIEW

**Review by markgoddard — CHANGES_REQUESTED** [review]
Looks good, needs a docs update. docs/source/configuration/networking.rst

**Review by markgoddard — APPROVED** [review]

**Review by markgoddard — CHANGES_REQUESTED** [review]
More docs please.

**Comment by jpds** [comment]
Already done.

**Review by markgoddard — APPROVED** [review]
Ta

**Pull request merged**
