### PR TITLE
Setup Travis CI

### PR DESCRIPTION
**Pull request by markgoddard**
No more broken builds!

### CODE REVIEW

**Comment by markgoddard** [comment]
Note 'All checks have passed' above.

**Comment by oneswig** [comment]
Travis might say it's passed but it doesn't look like a bed of roses in the log: https://travis-ci.org/stackhpc/kayobe/builds/271624127?utm_source=github_status&utm_medium=notification

**Comment by markgoddard** [comment]
You mean the error messages in the unit test output? That's normal test output, although I agree it's not ideal.

**Review by oneswig — APPROVED** [review]
I'll take your word that it's testing (and interpreting the results) correctly.  It's a worthwhile direction of travel.

**Pull request merged**
